-- Create audit table and trigger to record changes to Habilitado_Asig
-- WARNING: Run as table owner; adjust schema names if needed.

CREATE TABLE Habilitado_Asig_Audit (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cedula_usuario VARCHAR2(32),
    old_val NUMBER,
    new_val NUMBER,
    changed_by VARCHAR2(128),
    changed_at TIMESTAMP DEFAULT SYSTIMESTAMP,
    reason VARCHAR2(256)
);
/

-- Trigger to log updates
CREATE OR REPLACE TRIGGER TRG_USUARIO_HABILITADO_AUDIT
BEFORE UPDATE OF Habilitado_Asig ON Usuario
FOR EACH ROW
DECLARE
    v_user varchar2(128);
BEGIN
    -- capture current user
    BEGIN SELECT SYS_CONTEXT('USERENV','SESSION_USER') INTO v_user FROM DUAL; EXCEPTION WHEN OTHERS THEN v_user := NULL; END;
    IF NVL(:OLD.Habilitado_Asig, -1) <> NVL(:NEW.Habilitado_Asig, -1) THEN
        INSERT INTO Habilitado_Asig_Audit (cedula_usuario, old_val, new_val, changed_by, reason)
        VALUES (:OLD.Cedula_Usuario, :OLD.Habilitado_Asig, :NEW.Habilitado_Asig, v_user, 'triggered by application');
    END IF;
END;
/

-- Optional: grant select on audit table to reporting user
-- GRANT SELECT ON Habilitado_Asig_Audit TO REPORTING_USER;
